-- UI and visual plugins

return {
  -- HecateShell colors (generated by matugen)
  { import = 'plugins.hecate-colors' },

  -- Useful plugin to show pending keybinds
  {
    'folke/which-key.nvim',
    event = 'VimEnter',
    opts = {
      delay = 0,
      icons = {
        mappings = vim.g.have_nerd_font,
        keys = vim.g.have_nerd_font and {} or {
          Up = '<Up> ',
          Down = '<Down> ',
          Left = '<Left> ',
          Right = '<Right> ',
          C = '<C-…> ',
          M = '<M-…> ',
          D = '<D-…> ',
          S = '<S-…> ',
          CR = '<CR> ',
          Esc = '<Esc> ',
          ScrollWheelDown = '<ScrollWheelDown> ',
          ScrollWheelUp = '<ScrollWheelUp> ',
          NL = '<NL> ',
          BS = '<BS> ',
          Space = '<Space> ',
          Tab = '<Tab> ',
          F1 = '<F1>',
          F2 = '<F2>',
          F3 = '<F3>',
          F4 = '<F4>',
          F5 = '<F5>',
          F6 = '<F6>',
          F7 = '<F7>',
          F8 = '<F8>',
          F9 = '<F9>',
          F10 = '<F10>',
          F11 = '<F11>',
          F12 = '<F12>',
        },
      },
      spec = {
        { '<leader>s', group = '[S]earch' },
        { '<leader>t', group = '[T]oggle' },
        { '<leader>h', group = 'Git [H]unk', mode = { 'n', 'v' } },
      },
    },
  },

  -- Highlight todo, notes, etc in comments
  {
    'folke/todo-comments.nvim',
    event = 'VimEnter',
    dependencies = { 'nvim-lua/plenary.nvim' },
    opts = { signs = false },
  },

  -- Mini.nvim suite - textobjects and surroundings
  {
    'echasnovski/mini.nvim',
    config = function()
      -- Better Around/Inside textobjects
      -- Examples:
      --  - va)  - [V]isually select [A]round [)]paren
      --  - yinq - [Y]ank [I]nside [N]ext [Q]uote
      --  - ci'  - [C]hange [I]nside [']quote
      require('mini.ai').setup { n_lines = 500 }

      -- Add/delete/replace surroundings (brackets, quotes, etc.)
      -- - saiw) - [S]urround [A]dd [I]nner [W]ord [)]Paren
      -- - sd'   - [S]urround [D]elete [']quotes
      -- - sr)'  - [S]urround [R]eplace [)] [']
      require('mini.surround').setup()
    end,
  },

  -- Beautiful statusline with powerline arrows
  {
    'nvim-lualine/lualine.nvim',
    dependencies = { 'nvim-tree/nvim-web-devicons' },
    opts = {
      options = {
        theme = 'auto',
        component_separators = { left = '', right = '' },
        section_separators = { left = '', right = '' },
        globalstatus = true,
        disabled_filetypes = { statusline = { 'alpha' } },
      },
      sections = {
        lualine_a = { 'mode' },
        lualine_b = { 'branch', 'diff', 'diagnostics' },
        lualine_c = { 'filename' },
        lualine_x = { 'encoding', 'fileformat', 'filetype' },
        lualine_y = { 'progress' },
        lualine_z = { 'location' },
      },
      inactive_sections = {
        lualine_a = {},
        lualine_b = {},
        lualine_c = { 'filename' },
        lualine_x = { 'location' },
        lualine_y = {},
        lualine_z = {},
      },
    },
  },

  -- Start screen with recent files and projects
  {
    'goolord/alpha-nvim',
    event = 'VimEnter',
    dependencies = { 'nvim-tree/nvim-web-devicons' },
    config = function()
      local alpha = require 'alpha'
      local dashboard = require 'alpha.themes.dashboard'

      -- Header
      dashboard.section.header.val = {
        [[                                                    ]],
        [[ ██╗  ██╗███████╗ ██████╗ █████╗ ████████╗███████╗ ]],
        [[ ██║  ██║██╔════╝██╔════╝██╔══██╗╚══██╔══╝██╔════╝ ]],
        [[ ███████║█████╗  ██║     ███████║   ██║   █████╗   ]],
        [[ ██╔══██║██╔══╝  ██║     ██╔══██║   ██║   ██╔══╝   ]],
        [[ ██║  ██║███████╗╚██████╗██║  ██║   ██║   ███████╗ ]],
        [[ ╚═╝  ╚═╝╚══════╝ ╚═════╝╚═╝  ╚═╝   ╚═╝   ╚══════╝ ]],
        [[                                                    ]],
        [[              N E O V I M   C O N F I G            ]],
      }

      -- Buttons
      dashboard.section.buttons.val = {
        dashboard.button('f', '  Find file', ':Telescope find_files <CR>'),
        dashboard.button('n', '  New file', ':ene <BAR> startinsert <CR>'),
        dashboard.button('r', '  Recent files', ':Telescope oldfiles <CR>'),
        dashboard.button('g', '  Find text', ':Telescope live_grep <CR>'),
        dashboard.button('c', '  Config', ':e $MYVIMRC <CR>'),
        dashboard.button('s', '  Restore Session', ':SessionRestore<CR>'),
        dashboard.button('q', '  Quit', ':qa<CR>'),
      }

      -- Footer
      local function footer()
        local total_plugins = require('lazy').stats().count
        return '   Loaded ' .. total_plugins .. ' plugins'
      end

      dashboard.section.footer.val = footer()

      alpha.setup(dashboard.opts)

      -- Disable folding on alpha buffer
      vim.cmd [[autocmd FileType alpha setlocal nofoldenable]]
    end,
  },

  -- Terminal toggle - VSCode-like console at bottom
  {
    'akinsho/toggleterm.nvim',
    version = '*',
    opts = {
      size = function(term)
        if term.direction == 'horizontal' then
          return 15
        elseif term.direction == 'vertical' then
          return vim.o.columns * 0.4
        end
      end,
      open_mapping = [[<c-\>]],
      hide_numbers = true,
      shade_terminals = true,
      start_in_insert = true,
      insert_mappings = true,
      terminal_mappings = true,
      persist_size = true,
      persist_mode = true,
      direction = 'horizontal', -- 'vertical' | 'horizontal' | 'tab' | 'float'
      close_on_exit = true,
      shell = vim.o.shell,
      auto_scroll = true,
      float_opts = {
        border = 'curved',
        winblend = 0,
      },
    },
    config = function(_, opts)
      require('toggleterm').setup(opts)

      -- Keymaps for terminal mode
      function _G.set_terminal_keymaps()
        local opts_keymap = { buffer = 0 }
        vim.keymap.set('t', '<esc>', [[<C-\><C-n>]], opts_keymap)
        vim.keymap.set('t', 'jk', [[<C-\><C-n>]], opts_keymap)
        vim.keymap.set('t', '<C-h>', [[<Cmd>wincmd h<CR>]], opts_keymap)
        vim.keymap.set('t', '<C-j>', [[<Cmd>wincmd j<CR>]], opts_keymap)
        vim.keymap.set('t', '<C-k>', [[<Cmd>wincmd k<CR>]], opts_keymap)
        vim.keymap.set('t', '<C-l>', [[<Cmd>wincmd l<CR>]], opts_keymap)
        vim.keymap.set('t', '<C-w>', [[<C-\><C-n><C-w>]], opts_keymap)
      end

      vim.cmd 'autocmd! TermOpen term://* lua set_terminal_keymaps()'

      -- Custom terminal commands
      local Terminal = require('toggleterm.terminal').Terminal

      -- Lazygit terminal
      local lazygit = Terminal:new {
        cmd = 'lazygit',
        dir = 'git_dir',
        direction = 'float',
        float_opts = {
          border = 'curved',
        },
        on_open = function(term)
          vim.cmd 'startinsert!'
          vim.api.nvim_buf_set_keymap(term.bufnr, 'n', 'q', '<cmd>close<CR>', { noremap = true, silent = true })
        end,
      }

      function _LAZYGIT_TOGGLE()
        lazygit:toggle()
      end

      -- Keymaps
      vim.keymap.set('n', '<leader>tt', '<cmd>ToggleTerm<cr>', { desc = '[T]oggle [T]erminal' })
      vim.keymap.set('n', '<leader>tf', '<cmd>ToggleTerm direction=float<cr>', { desc = '[T]erminal [F]loat' })
      vim.keymap.set('n', '<leader>tv', '<cmd>ToggleTerm direction=vertical<cr>', { desc = '[T]erminal [V]ertical' })
      vim.keymap.set('n', '<leader>tg', '<cmd>lua _LAZYGIT_TOGGLE()<CR>', { desc = '[T]oggle lazy[g]it' })
    end,
  },
}
