pragma Singleton
import QtQuick
import Quickshell
import Quickshell.Io

QtObject {
    id: config

    // Get user's home directory from environment
    property string homeDir: Quickshell.env("HOME")
    property string configPath: homeDir + "/.config/HecateShell/config"

    // Bar Configuration
    property int barHeight: 35
    property color barBackground: "#1e1e2e"
    property int barBorderRadius: 0

    // Typography
    property string fontFamily: "JetBrains Mono"
    property int fontSize: 12
    property int fontSizeLarge: 14
    property int fontSizeSmall: 10

    // Colors - Loaded from colors.conf (generated by matugen)
    property color textColor: "#cdd6f4"
    property color textColorDim: "#a6adc8"
    property color accentColor: "#89b4fa"
    property color accentColorAlt: "#f5c2e7"
    property color backgroundColor: "#1e1e2e"
    property color backgroundColorAlt: "#313244"
    property color borderColor: "#45475a"

    // Widget specific colors
    property color workspaceActive: "#89b4fa"
    property color workspaceInactive: "#45475a"
    property color visualizerColor: "#89b4fa"

    // Spacing & Padding
    property int paddingSmall: 4
    property int paddingMedium: 8
    property int paddingLarge: 12
    property int spacing: 8

    // Music Visualizer
    property int visualizerWidth: 200
    property int visualizerHeight: 3
    property int visualizerBarCount: 20
    property int visualizerBarSpacing: 2

    // Icons (using Unicode for now, can switch to icon fonts later)
    property string iconVolume: "󰕾"
    property string iconVolumeMuted: "󰖁"
    property string iconWifiOn: "󰖩"
    property string iconWifiOff: "󰖪"

    property string lastFileContent: ""
    property var colorReloadTimer: null
    property var colorLoaderProcess: null

    function loadColors() {
        if (!colorLoaderProcess) {
            var colorsPath = configPath + "/colors.conf"
            colorLoaderProcess = Qt.createQmlObject('
                import Quickshell.Io
                Process {
                    property string colorsFile: "' + colorsPath + '"
                    command: ["cat", colorsFile]
                    stdout: SplitParser {
                        onRead: function(data) {
                            checkAndParseColors(data)
                        }
                    }
                }
            ', config)
        }
        colorLoaderProcess.running = true
    }

    function checkAndParseColors(data) {
        if (data !== lastFileContent) {
            lastFileContent = data
            parseColors(data)
        }
    }

    function parseColors(data) {
        var lines = data.split("\n")
        for (var i = 0; i < lines.length; i++) {
            var line = lines[i].trim()
            // Skip comments and empty lines
            if (line.startsWith("#") || line === "") continue

            var parts = line.split("=")
            if (parts.length !== 2) continue

            var key = parts[0].trim()
            var value = parts[1].trim()

            // Update color properties
            switch(key) {
                case "barBackground":
                    config.barBackground = value
                    break
                case "backgroundColor":
                    config.backgroundColor = value
                    break
                case "backgroundColorAlt":
                    config.backgroundColorAlt = value
                    break
                case "borderColor":
                    config.borderColor = value
                    break
                case "textColor":
                    config.textColor = value
                    break
                case "textColorDim":
                    config.textColorDim = value
                    break
                case "accentColor":
                    config.accentColor = value
                    break
                case "accentColorAlt":
                    config.accentColorAlt = value
                    break
                case "workspaceActive":
                    config.workspaceActive = value
                    break
                case "workspaceInactive":
                    config.workspaceInactive = value
                    break
                case "visualizerColor":
                    config.visualizerColor = value
                    break
            }
        }
    }

    Component.onCompleted: {
        console.log("Shell config loaded")
        loadColors() // Load colors on startup

        // Create timer for hot-reloading colors
        colorReloadTimer = Qt.createQmlObject('
            import QtQuick
            Timer {
                interval: 1000
                running: true
                repeat: true
            }
        ', config)
        colorReloadTimer.triggered.connect(loadColors)
    }
}
