pragma Singleton
import QtQuick
import Quickshell
import Quickshell.Io
import "." as ConfigModule

QtObject {
    id: config

    // Get user's home directory from environment
    property string homeDir: Quickshell.env("HOME")
    property string configPath: homeDir + "/.config/HecateShell/config"

    // Color loader component
    property var loader: ConfigModule.ColorLoader {
        onColorsLoaded: function(data) {
            var fullData = data.trim()
            if (fullData && fullData !== config.lastFileContent) {
                console.log("Theme updated")
                config.lastFileContent = fullData
                config.parseColors(fullData)
            }
        }
    }

    // Bar Configuration
    property int barHeight: 35
    property int barBorderRadius: 0

    // Typography
    property string fontFamily: "JetBrains Mono"
    property int fontSize: 12
    property int fontSizeLarge: 14
    property int fontSizeSmall: 10

    // Colors - Loaded from theme.json (generated by matugen)
    property color textColor: "#cdd6f4"
    property color textColorDim: "#a6adc8"
    property color accentColor: "#89b4fa"
    property color backgroundColor: "#1e1e2e"
    property color backgroundColorAlt: "#313244"
    property color borderColor: "#45475a"

    // Spacing & Padding
    property int paddingSmall: 4
    property int paddingMedium: 8
    property int paddingLarge: 12
    property int spacing: 8

    // Workspace indicator
    property int workspaceItemSize: barHeight - paddingSmall * 4

    // Music Visualizer
    property int visualizerWidth: 200
    property int visualizerHeight: 3
    property int visualizerBarCount: 20
    property int visualizerBarSpacing: 2

    // Wallpaper (swww)
    property string swwwTransition: "fade"
    property int swwwDuration: 1

    // Icons (using Unicode for now, can switch to icon fonts later)
    property string iconVolume: "󰕾"
    property string iconVolumeMuted: "󰖁"
    property string iconWifiOn: "󰖩"
    property string iconWifiOff: "󰖪"

    property string lastFileContent: ""
    property var colorReloadTimer: null

    function loadColors() {
        var themePath = homeDir + "/.config/HecateShell/theme.json"
        loader.load(themePath)
    }

    function parseColors(data) {
        try {
            var theme = JSON.parse(data)

            // Map Material Design 3 colors to our theme
            config.backgroundColor = theme.surface
            config.backgroundColorAlt = theme.surfaceContainer
            config.borderColor = theme.outline
            config.textColor = theme.surfaceText
            config.textColorDim = theme.surfaceVariantText
            config.accentColor = theme.primary
        } catch (e) {
            console.error("Failed to parse theme.json:", e)
        }
    }

    // Smooth color transitions
    Behavior on backgroundColor { ColorAnimation { duration: 300; easing.type: Easing.InOutQuad } }
    Behavior on backgroundColorAlt { ColorAnimation { duration: 300; easing.type: Easing.InOutQuad } }
    Behavior on borderColor { ColorAnimation { duration: 300; easing.type: Easing.InOutQuad } }
    Behavior on textColor { ColorAnimation { duration: 300; easing.type: Easing.InOutQuad } }
    Behavior on textColorDim { ColorAnimation { duration: 300; easing.type: Easing.InOutQuad } }
    Behavior on accentColor { ColorAnimation { duration: 300; easing.type: Easing.InOutQuad } }

    Component.onCompleted: {
        loadColors() // Load colors on startup

        // Create timer for hot-reloading colors
        colorReloadTimer = Qt.createQmlObject('
            import QtQuick
            Timer {
                interval: 1000
                running: true
                repeat: true
            }
        ', config)
        colorReloadTimer.triggered.connect(loadColors)
    }
}
