package vscode

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
)

const extensionID = "hecateshell.hecate-theme"
const extensionVersion = "1.0.0"
const extensionDir = "hecate-theme"

// ExtensionEntry represents an entry in extensions.json
type ExtensionEntry struct {
	Identifier       ExtensionIdentifier `json:"identifier"`
	Version          string              `json:"version"`
	Location         ExtensionLocation   `json:"location"`
	RelativeLocation string              `json:"relativeLocation"`
}

type ExtensionIdentifier struct {
	ID string `json:"id"`
}

type ExtensionLocation struct {
	Mid    int    `json:"$mid"`
	Path   string `json:"path"`
	Scheme string `json:"scheme"`
}

// InstallThemeExtension installs the HecateShell VSCode theme extension
func InstallThemeExtension() error {
	homeDir := os.Getenv("HOME")
	vscodeDir := filepath.Join(homeDir, ".vscode")

	// Check if VSCode is installed
	if _, err := os.Stat(vscodeDir); os.IsNotExist(err) {
		// VSCode not installed, skip silently
		return nil
	}

	extensionsDir := filepath.Join(vscodeDir, "extensions")
	themeDir := filepath.Join(extensionsDir, extensionDir)
	themesDir := filepath.Join(themeDir, "themes")

	// Create directory structure
	if err := os.MkdirAll(themesDir, 0755); err != nil {
		return fmt.Errorf("failed to create extension directory: %w", err)
	}

	// Write package.json
	if err := writePackageJson(themeDir); err != nil {
		return fmt.Errorf("failed to write package.json: %w", err)
	}

	// Update extensions.json
	if err := updateExtensionsJson(extensionsDir, themeDir); err != nil {
		return fmt.Errorf("failed to update extensions.json: %w", err)
	}

	return nil
}

// writePackageJson writes the extension manifest
func writePackageJson(themeDir string) error {
	packageJson := map[string]interface{}{
		"name":        "hecate-theme",
		"displayName": "HecateShell Theme",
		"description": "Dynamic color scheme generated by HecateShell",
		"version":     extensionVersion,
		"publisher":   "hecateshell",
		"engines": map[string]string{
			"vscode": "^1.70.0",
		},
		"categories": []string{"Themes"},
		"contributes": map[string]interface{}{
			"themes": []map[string]string{
				{
					"label":   "HecateShell Dark",
					"uiTheme": "vs-dark",
					"path":    "./themes/hecate-dark.json",
				},
			},
		},
	}

	data, err := json.MarshalIndent(packageJson, "", "  ")
	if err != nil {
		return err
	}

	return os.WriteFile(filepath.Join(themeDir, "package.json"), data, 0644)
}

// updateExtensionsJson adds the extension to VSCode's extensions.json if not present
func updateExtensionsJson(extensionsDir, themeDir string) error {
	extensionsJsonPath := filepath.Join(extensionsDir, "extensions.json")

	var extensions []ExtensionEntry

	// Read existing extensions.json if it exists
	if data, err := os.ReadFile(extensionsJsonPath); err == nil {
		if err := json.Unmarshal(data, &extensions); err != nil {
			// If parsing fails, start fresh
			extensions = []ExtensionEntry{}
		}
	}

	// Check if our extension is already registered
	for _, ext := range extensions {
		if ext.Identifier.ID == extensionID {
			// Already registered, nothing to do
			return nil
		}
	}

	// Add our extension entry
	newEntry := ExtensionEntry{
		Identifier: ExtensionIdentifier{
			ID: extensionID,
		},
		Version: extensionVersion,
		Location: ExtensionLocation{
			Mid:    1,
			Path:   themeDir,
			Scheme: "file",
		},
		RelativeLocation: extensionDir,
	}

	extensions = append(extensions, newEntry)

	// Write back
	data, err := json.MarshalIndent(extensions, "", "")
	if err != nil {
		return err
	}

	return os.WriteFile(extensionsJsonPath, data, 0644)
}

// IsInstalled checks if the VSCode theme extension is installed
func IsInstalled() bool {
	homeDir := os.Getenv("HOME")
	packageJsonPath := filepath.Join(homeDir, ".vscode", "extensions", extensionDir, "package.json")
	_, err := os.Stat(packageJsonPath)
	return err == nil
}
